name: FC_Suite_Shared
main: me.Destro168.FC_Suite_Shared.FC_Suite_Shared
version: 2.3
description: Manages various FC plugins.
commands:
   FCinfo:
      description: The about command for all FC plugins.
softdepend: [Essentials]
depend: [Vault]